language: node_js

node_js:
  - 4
  - 6
  - 8

env:
  - ARANGODB_VERSION=2.8
  - ARANGODB_VERSION=3.1
  - ARANGODB_VERSION=3.2
  - ARANGODB_VERSION=3.3

before_install:
- docker pull arangodb:$ARANGODB_VERSION
- docker run -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb:$ARANGODB_VERSION

after_success:
  - npm run coverage:ci

branches:
  only:
    - master
    - 2.x