language: node_js

node_js:
  - 4
  - 6
  - 8

env:
  - ARANGODB_VERSION=2.8
  - ARANGODB_VERSION=3.1
  - ARANGODB_VERSION=3.2
  - ARANGODB_VERSION=3.3

before_install:
  - chmod +x ./test/travis/setup_arangodb.sh
  - ./test/travis/setup_arangodb.sh

after_success:
  - npm run coverage:ci

after_script:
  - ./test/travis/teardown_arangodb.sh

branches:
  only:
    - master
    - 2.x